[package]
name = "libleaf"
version = "0.1.0"
edition = "2021"

[lib]
name = "leaf"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.24.3"

[dependencies]
indicatif = "0.17.3"
once_cell = "1.17.1"
curl = "0.4.44"
log = "0.4.17"
pretty_env_logger = "0.4.0"
