[package]
name = "libleaf"
version = "0.1.0"
edition = "2021"

[lib]
name = "leaf"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.24.3"

[dependencies]
indicatif = "0.17.3"
    